server.port=8185
server.servlet.context-path=/

# Spring Application
spring.application.name=utils-service

jwt.secret=CISeA6wgEpnKgCkyfagPOGobDhe3FwXiM7dRfIwWbLXAPlog5LJn5dZOEgI1r5c95BiPw1zA7/vylBKRkRlcBg==

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/post_hub_local
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.default_schema=v1_utils_service
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_utils_service

#Logging Level
logging.level.com.post_hub.iam_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG 

swagger.servers.first=http://localhost:8185
swagger.servers.second
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#End points
end.point.logs=/logs
end.point.id=/{id}
end.point.search=/search
end.point.all=/all
end.point.markAsRead=/markAsRead
