server.port=8185
server.servlet.context-path=/

# Spring Application
spring.application.name=utils-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/post_hub_local
spring.datasource.username=postgres
spring.datasource.password=Kolya8787
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.default_schema=v1_utils_service
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_utils_service


# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=utils-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.post_hub.utils_service.model.dto.kafka.UserEvent

# Logging Level
logging.level.com.post_hub.iam_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
